# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Bootstrap CLI for the VLM Feedback Loop.

Usage:
    vlm-feedback-loop init                      Create config directory, config.yaml, and .env
    vlm-feedback-loop tao-bootstrap             Provision a TAO workspace (+ base experiments per mode)
    vlm-feedback-loop tao-pull-base-experiments Self-service base-experiment provisioning
"""

from __future__ import annotations

import argparse
import asyncio
import contextlib
import json
import os
import stat
import sys
from collections.abc import Callable, Sequence
from importlib import import_module, util
from pathlib import Path
from typing import Any, cast

import yaml

from vlm_feedback_loop._defaults import DEFAULTS, SECRET_KEYS
from vlm_feedback_loop.model_catalog_constants import (
    COSMOS3_NANO_REASONER,
    COSMOS3_SUPER_REASONER,
    COSMOS_REASON2_2B,
    COSMOS_REASON2_8B,
)

_CONFIG_DIR: Path = Path.home() / ".vlm_feedback_loop"
_CONFIG_FILE: Path = _CONFIG_DIR / "config.yaml"
_ENV_FILE: Path = _CONFIG_DIR / ".env"


def _write_config_yaml(workspace_root: str) -> None:
    """Write config.yaml with WORKSPACE_ROOT as the only active key.

    Every other non-secret A.4 default is emitted as a commented
    documentation line. Any key active in config.yaml is an operator
    override that pins its install-date value forever — a full snapshot
    would silently shadow every future default change, so defaults stay
    commented and keep tracking the shipped values across upgrades.
    """
    lines: list[str] = [
        "# Interactive VLM Feedback Loop — application configuration",
        "# Generated by 'vlm-feedback-loop init'.",
        "#",
        "# Only WORKSPACE_ROOT is active. Every other setting below is a",
        "# commented-out copy of its built-in default — uncomment a line only",
        "# to override it. A key that stays commented keeps tracking the",
        "# shipped default across upgrades; an uncommented key pins the value",
        "# written here, even when a later release changes the default.",
        "#",
        "# Secrets (API keys, NGC/TAO credentials, the HuggingFace token)",
        "# belong in ~/.vlm_feedback_loop/.env — see .env.example.",
        "",
        yaml.dump({"WORKSPACE_ROOT": workspace_root}, default_flow_style=False).rstrip(
            "\n"
        ),
        "",
        "# ── Built-in defaults (uncomment to override) ──────────────────────",
    ]
    for key, value in DEFAULTS.items():
        if key in SECRET_KEYS:
            continue
        dumped = yaml.dump({key: value}, default_flow_style=False, sort_keys=False)
        lines.extend(f"# {dline}" for dline in dumped.rstrip("\n").splitlines())

    with open(_CONFIG_FILE, "w") as f:
        f.write("\n".join(lines) + "\n")


def _write_skeleton_env() -> None:
    """Write a commented .env skeleton documenting required secret variables."""
    content = """\
# VLM Feedback Loop — Secrets
#
# Generated by 'vlm-feedback-loop init'.
# Uncomment and fill in values for your deployment.

# NVIDIA Hosted NIM (required for hosted Teacher inference and embeddings)
# Get a key at https://build.nvidia.com/settings/api-keys
# NVIDIA_API_KEY=nvapi-...

# NGC (required for local NIM container pulls)
# Get a key at https://org.ngc.nvidia.com/setup/api-key
# NGC_API_KEY=

# TAO (required when Student Training is enabled)
# TAO_API_KEY=
# TAO_API_BASE_URL=https://<tao-host>/api/v2
# TAO_ORG_NAME=

# TAO workspace S3 credentials (required by tao-bootstrap when the
# FTMS deployment uses S3-backed workspaces — see docs/tao-ftms-install.md)
# TAO_WORKSPACE_S3_ACCESS_KEY=
# TAO_WORKSPACE_S3_SECRET_KEY=

# Hugging Face token (only needed for gated base-model pulls during
# Student training setup — see docs/tao-ftms-install.md)
# HF_TOKEN=
"""
    with open(_ENV_FILE, "w") as f:
        f.write(content)


def cmd_init(args: argparse.Namespace) -> None:
    """Bootstrap the configuration directory.

    Never clobbers silently: an existing ``config.yaml`` requires
    ``--force`` to overwrite, and an existing ``.env`` is NEVER
    overwritten (it holds the operator's API keys) — the skeleton is
    only written when the file is absent.
    """
    if _CONFIG_FILE.exists() and not getattr(args, "force", False):
        print(
            f"Refusing to overwrite existing {_CONFIG_FILE}.\n"
            "Re-run with --force to regenerate config.yaml "
            "(your .env and its API keys are preserved either way).",
            file=sys.stderr,
        )
        sys.exit(1)

    workspace_root = (getattr(args, "workspace_root", None) or "").strip()
    if not workspace_root:
        workspace_root = input(
            "Enter WORKSPACE_ROOT (absolute path for project data): "
        ).strip()

    if not workspace_root:
        print("Error: WORKSPACE_ROOT is required.", file=sys.stderr)
        sys.exit(1)
    workspace_root = os.path.expanduser(workspace_root)
    if not os.path.isabs(workspace_root):
        print(
            "Error: WORKSPACE_ROOT must be an absolute path.",
            file=sys.stderr,
        )
        sys.exit(1)

    _CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    with contextlib.suppress(OSError):  # best-effort on platforms without chmod
        os.chmod(_CONFIG_DIR, stat.S_IRWXU)  # 0o700

    _write_config_yaml(workspace_root)

    if _ENV_FILE.exists():
        print(f"Existing {_ENV_FILE} preserved (holds your API keys).")
    else:
        _write_skeleton_env()
        with contextlib.suppress(OSError):  # best-effort on platforms without chmod
            os.chmod(_ENV_FILE, stat.S_IRUSR | stat.S_IWUSR)  # 0o600

    workspace_path = Path(workspace_root)
    workspace_path.mkdir(parents=True, exist_ok=True)

    from vlm_feedback_loop.db.engine import init_deployment_db

    init_deployment_db(workspace_path)

    print(f"Configuration written to {_CONFIG_FILE}")
    print(f"Skeleton .env written to {_ENV_FILE}")
    print(f"Deployment database initialized at {workspace_path / 'deployment.db'}")
    print("Edit the .env file to add your API keys.")


# ── tao-bootstrap ───────────────────────────────────────────────────────────


# Lives in ``services.tao_bootstrap_service`` so the self-service
# provisioning path can reuse the same writers without importing CLI
# argparse code.
from vlm_feedback_loop.services.tao_bootstrap_service import (  # noqa: E402 — import below module-level CLI constants
    patch_model_configs_across_projects,
)


async def _run_tao_bootstrap(
    *,
    workspace_name: str,
    cloud_type: str,
    bucket: str,
    s3_endpoint_url_external: str,
    s3_endpoint_url_internal: str,
    _settings_loader: Any = None,
    _workspace_service: Any = None,
) -> None:
    """Async orchestration core of ``tao-bootstrap``. Unit-testable.

    Creates (or adopts) the TAO workspace using S3 credentials already loaded
    from Settings. Base-experiment provisioning is NOT part of this core:
    stock FTMS exposes no client-driven ``:pull_from_ngc`` route (live
    OpenAPI probes, 6.25.11 and 6.26.3) — the self-service path goes
    through ``provision_base_experiments`` and the admin-managed path
    patches admin-supplied UUIDs, both in ``cmd_tao_bootstrap``.

    ``_settings_loader`` and ``_workspace_service`` are injectable for
    tests so the CLI tests do not need a live TAO endpoint. Default
    production path loads the real settings singleton and calls the
    real ``tao_workspace_service``.
    """
    from vlm_feedback_loop import config as config_mod
    from vlm_feedback_loop.db.engine import init_deployment_db
    from vlm_feedback_loop.services import tao_workspace_service as ws_svc

    if _workspace_service is None:
        _workspace_service = ws_svc

    # 1) Load settings from the normal precedence chain. Process-only
    #    credentials must remain process-only; bootstrap never patches .env.
    if _settings_loader is None:
        config_mod.reset_settings()
        settings = config_mod.load_settings()
    else:
        settings = _settings_loader()

    # Credentials must already come from the process environment or canonical
    # .env. Validate before initializing deployment.db or contacting TAO so a
    # missing secret cannot leave a partial bootstrap state.
    s3_access_key = (settings.TAO_WORKSPACE_S3_ACCESS_KEY or "").strip()
    s3_secret_key = (settings.TAO_WORKSPACE_S3_SECRET_KEY or "").strip()
    missing = [
        name
        for name, value in (
            ("TAO_WORKSPACE_S3_ACCESS_KEY", s3_access_key),
            ("TAO_WORKSPACE_S3_SECRET_KEY", s3_secret_key),
        )
        if not value
    ]
    if missing:
        raise RuntimeError(
            "Set required TAO workspace S3 credential environment variable(s): "
            + ", ".join(missing)
        )

    workspace_root = Path(settings.WORKSPACE_ROOT)
    init_deployment_db(workspace_root)

    # 2) Mark bootstrap_status as in_progress.
    _update_tao_deployment_config(
        workspace_root, bootstrap_status="in_progress", bootstrap_error_ref=None
    )

    # 3) Create (or get) the TAO workspace. Process-only credentials remain
    # process-only; file-backed credentials were loaded from the operator's
    # existing .env. Bootstrap never changes that persistence choice.
    workspace_result = await _workspace_service.create_or_get_workspace(
        settings,
        workspace_name=workspace_name,
        cloud_type=cloud_type,
        bucket=bucket,
        endpoint_url_external=s3_endpoint_url_external,
        endpoint_url_internal=s3_endpoint_url_internal,
        access_key=s3_access_key,
        secret_key=s3_secret_key,
    )

    if not workspace_result.success:
        safe_error = workspace_result.error or "unknown workspace error"
        for credential in sorted(
            {s3_access_key, s3_secret_key},
            key=len,
            reverse=True,
        ):
            safe_error = safe_error.replace(credential, "[REDACTED]")
        _update_tao_deployment_config(
            workspace_root,
            bootstrap_status="failed",
            bootstrap_error_ref=f"Workspace create failed: {safe_error}",
        )
        raise RuntimeError(f"TAO workspace create failed: {safe_error}")

    workspace_id = workspace_result.workspace_id
    assert workspace_id is not None

    # Idempotent shortcut: already bootstrapped → report state + exit.
    if workspace_result.already_provisioned:
        print(
            f"Already bootstrapped (workspace_id={workspace_id}); the "
            "workspace record in deployment.db is the source of truth. "
            "Re-running tao-bootstrap adopts the existing workspace and does "
            "not refresh base-experiment state (run "
            "`vlm-feedback-loop tao-pull-base-experiments` for that). To "
            "re-provision from scratch, clear the persisted TAO workspace "
            "record in deployment.db and run tao-bootstrap again."
        )
        _update_tao_deployment_config(workspace_root, bootstrap_status="bootstrapped")
        return

    # 4) Persist success state on the singleton.
    _update_tao_deployment_config(
        workspace_root,
        bootstrap_status="bootstrapped",
        bootstrap_last_run_at=_now_utc(),
    )

    print(f"TAO workspace created: {workspace_id}")
    print(
        "Bootstrap complete. Workspace state persisted to deployment.db; "
        "S3 credentials remain in their configured environment source."
    )


def _update_tao_deployment_config(workspace_root: Path, **fields: object) -> None:
    """Apply field updates to the TAODeploymentConfig singleton."""
    from sqlalchemy.orm import Session

    from vlm_feedback_loop.db.deployment_models import TAODeploymentConfig
    from vlm_feedback_loop.db.engine import init_deployment_db

    engine = init_deployment_db(workspace_root)
    with Session(engine) as session:
        cfg = session.query(TAODeploymentConfig).first()
        assert cfg is not None, "TAODeploymentConfig singleton missing"
        for key, value in fields.items():
            setattr(cfg, key, value)
        session.commit()


def _now_utc() -> str:
    from vlm_feedback_loop.db.base import utc_now

    return utc_now()


def cmd_tao_bootstrap(args: argparse.Namespace) -> None:
    """Provision a TAO workspace and configure the base-provisioning mode.

    One-time admin operation per TAO deployment. Idempotent:
    re-running against an already-provisioned deployment reports current
    state without re-issuing TAO calls.

    Two modes:

    - ``--self-service`` (default) — create the workspace; Student Training
      provisions each selected missing base on first use.
      ``--eager-bases`` additionally pulls every supported base now.
    - ``--admin-managed`` — create the workspace and stop.
      The admin pulls base experiments off-Blueprint; the operator
      passes the resulting UUIDs via ``--base-experiment-id-*``
      and this CLI patches them across every project DB without any
      NGC/HF download.
    """
    if getattr(args, "admin_managed", False) and getattr(args, "eager_bases", False):
        print(
            "tao-bootstrap failed: --eager-bases is only valid in self-service mode",
            file=sys.stderr,
        )
        sys.exit(2)

    try:
        asyncio.run(
            _run_tao_bootstrap(
                workspace_name=args.workspace_name,
                cloud_type=args.cloud_type,
                bucket=args.bucket,
                s3_endpoint_url_external=args.s3_endpoint_url_external,
                s3_endpoint_url_internal=args.s3_endpoint_url_internal,
            )
        )
    except Exception as exc:  # surface a clean error exit
        print(f"tao-bootstrap failed: {exc}", file=sys.stderr)
        sys.exit(1)

    # ── branch on --self-service vs --admin-managed ──────────────────────────
    from vlm_feedback_loop import config as config_mod

    if getattr(args, "admin_managed", False):
        # Admin-managed mode — workspace created above; base experiments
        # stay admin-provisioned. If the operator supplied UUIDs via
        # --base-experiment-id-{2b,8b}, patch them across project DBs
        # so the standard training preflight accepts them.
        base_map: dict[str, str] = {}
        if args.base_experiment_id_2b:
            base_map[COSMOS_REASON2_2B] = args.base_experiment_id_2b
        if args.base_experiment_id_8b:
            base_map[COSMOS_REASON2_8B] = args.base_experiment_id_8b
        if getattr(args, "base_experiment_id_cosmos3_nano", None):
            base_map[COSMOS3_NANO_REASONER] = args.base_experiment_id_cosmos3_nano
        if getattr(args, "base_experiment_id_cosmos3_super", None):
            base_map[COSMOS3_SUPER_REASONER] = args.base_experiment_id_cosmos3_super
        if base_map:
            config_mod.reset_settings()
            settings = config_mod.load_settings()
            patched = patch_model_configs_across_projects(
                Path(settings.WORKSPACE_ROOT), base_experiment_map=base_map
            )
            for project_dir, count in patched:
                print(f"  Patched {count} ModelConfig row(s) in {project_dir.name}")
        print(
            "Workspace created in admin-managed mode. Base experiments are NOT "
            "provisioned by the Blueprint. See "
            "docs/tao-ftms-install.md (base-experiment registration) "
            "for the admin recipe."
        )
        return

    # Default self-service mode defers base weights until the SME selects a
    # model and clicks Start Training. Operators can still warm every base
    # eagerly for disconnected execution windows.
    if not getattr(args, "eager_bases", False):
        print(
            "Self-service workspace ready. Missing Student bases will be "
            "provisioned automatically when selected on Student Training. "
            "Use --eager-bases or `vlm-feedback-loop "
            "tao-pull-base-experiments` to warm all bases now."
        )
        return

    # Optional eager path: chain into all-base provisioning.
    from vlm_feedback_loop.services.tao_base_experiment_provisioning_service import (
        provision_base_experiments,
    )

    config_mod.reset_settings()
    settings = config_mod.load_settings()
    try:
        result = asyncio.run(provision_base_experiments(settings))
    except Exception as exc:
        print(
            f"tao-bootstrap base-experiment provisioning failed: {exc}", file=sys.stderr
        )
        sys.exit(1)

    print(
        json.dumps(
            {
                "registered": result.registered,
                "already_registered": result.already_registered,
                "failed": [{"target": t, "error": e} for t, e in result.failed],
            },
            indent=2,
        )
    )
    if result.failed:
        sys.exit(1)


# ── tao-pull-base-experiments ───────────────────────────────────────────────


def cmd_tao_pull_base_experiments(args: argparse.Namespace) -> None:
    """Self-service base-experiment provisioning.

    Resolves the operator's NGC Personal API Key (environment
    ``NGC_API_KEY`` → settings ``TAO_API_KEY``), checks that a TAO
    workspace is bootstrapped in deployment.db — the source of truth
    (``TAODeploymentConfig.tao_workspace_id``), selects the isolated
    helper environment (or the operator-managed current interpreter),
    then dispatches to the provisioning service.

    JSON output on stdout. Exit 0 on success; exit 1 on any failure.
    """
    from vlm_feedback_loop import config as config_mod
    from vlm_feedback_loop.services.tao_auth import TaoAuthError
    from vlm_feedback_loop.services.tao_base_experiment_provisioning_service import (
        provision_base_experiments,
    )

    # 1) Resolve NGC key precedence: NGC_API_KEY → settings.TAO_API_KEY.
    ngc_key = (os.environ.get("NGC_API_KEY") or "").strip()
    if not ngc_key:
        config_mod.reset_settings()
        probe_settings = config_mod.load_settings()
        ngc_key = (probe_settings.TAO_API_KEY or "").strip()
    if not ngc_key:
        print(
            "Error: NGC Personal API Key required. Set env NGC_API_KEY "
            "or TAO_API_KEY in your canonical .env.",
            file=sys.stderr,
        )
        sys.exit(1)

    # 2) Load settings + apply the resolved key (in-memory; no .env writes).
    config_mod.reset_settings()
    settings = config_mod.load_settings()
    settings.TAO_API_KEY = ngc_key

    # 3) Bail when the workspace isn't bootstrapped — provisioning depends
    #    on a populated TAODeploymentConfig (workspace_id + bucket).
    #    Source of truth is deployment.db, not .env.
    from sqlalchemy.orm import Session

    from vlm_feedback_loop.db.deployment_models import TAODeploymentConfig
    from vlm_feedback_loop.db.engine import init_deployment_db

    if not settings.WORKSPACE_ROOT:
        print(
            "Error: WORKSPACE_ROOT is not set; run `vlm-feedback-loop init` first.",
            file=sys.stderr,
        )
        sys.exit(1)
    _engine = init_deployment_db(settings.WORKSPACE_ROOT)
    with Session(_engine) as _session:
        _tao_cfg = _session.query(TAODeploymentConfig).first()
    if _tao_cfg is None or not _tao_cfg.tao_workspace_id:
        print(
            "Error: TAO workspace not bootstrapped (deployment.db has no "
            "tao_workspace_id). Run `vlm-feedback-loop tao-bootstrap "
            "--self-service` (default) or `tao-bootstrap --admin-managed` "
            "first to create the workspace before pulling base experiments.",
            file=sys.stderr,
        )
        sys.exit(1)

    # 4) Dispatch. By default the provisioning service uses an isolated,
    #    cached uv environment for TAO's packaging dependencies. This keeps
    #    their pins out of the FastAPI environment. Air-gapped operators that
    #    preinstalled the helper packages can retain the old direct-interpreter
    #    path with --skip-install.
    student_ids = list(args.model_config_id) if args.model_config_id else None
    hf_token = os.environ.get("HF_TOKEN") or os.environ.get("HUGGING_FACE_HUB_TOKEN")
    try:
        result = asyncio.run(
            provision_base_experiments(
                settings,
                student_base_model_config_ids=student_ids,
                hf_token=hf_token,
                subprocess_timeout_s=args.timeout_download_s,
                use_isolated_helper=not args.skip_install,
                _dry_run=args.dry_run,
            )
        )
    except TaoAuthError as exc:
        print(f"TAO authentication failed: {exc}", file=sys.stderr)
        sys.exit(1)
    except Exception as exc:
        print(f"tao-pull-base-experiments failed: {exc}", file=sys.stderr)
        sys.exit(1)

    print(
        json.dumps(
            {
                "registered": result.registered,
                "already_registered": result.already_registered,
                "failed": [{"target": t, "error": e} for t, e in result.failed],
                "dry_run": bool(args.dry_run),
            },
            indent=2,
        )
    )
    if result.failed:
        sys.exit(1)


def main(argv: Sequence[str] | None = None) -> None:
    """CLI entry point."""
    cli_argv = list(sys.argv[1:] if argv is None else argv)

    parser = argparse.ArgumentParser(
        prog="vlm-feedback-loop",
        description="Interactive VLM Feedback Loop CLI",
    )
    subparsers = parser.add_subparsers(dest="command")

    init_parser = subparsers.add_parser(
        "init", help="Initialize configuration directory"
    )
    init_parser.add_argument(
        "--force",
        action="store_true",
        help=(
            "Overwrite an existing config.yaml. The .env file (API keys) "
            "is never overwritten, with or without this flag."
        ),
    )
    init_parser.add_argument(
        "--workspace-root",
        help=(
            "Absolute path for project data (e.g. ~/vlm-workspace). "
            "Skips the interactive prompt — use for scripted/copy-paste setup."
        ),
    )
    init_parser.set_defaults(func=cmd_init)

    tao_parser = subparsers.add_parser(
        "tao-bootstrap",
        help="Provision a TAO workspace for Student Training",
    )
    tao_parser.add_argument("--workspace-name", required=True)
    tao_parser.add_argument(
        "--cloud-type",
        default="seaweedfs",
        choices=[
            "seaweedfs",
            "aws",
            "azure",
            "self_hosted",
            "huggingface",
            "lepton",
            "slurm",
        ],
    )
    tao_parser.add_argument("--bucket", required=True)
    tao_parser.add_argument(
        "--s3-endpoint-url-external",
        default="http://127.0.0.1:8333",
        help=(
            "S3 endpoint URL the Blueprint uses to upload. Defaults to the "
            "SeaweedFS-bundled compose default."
        ),
    )
    tao_parser.add_argument(
        "--s3-endpoint-url-internal",
        default="http://seaweedfs-s3:8333",
        help=(
            "S3 endpoint URL TAO's containers use to read. Defaults to "
            "the SeaweedFS-bundled compose default."
        ),
    )
    tao_parser.add_argument(
        "--base-experiment-id-8b",
        default=None,
        help=(
            "Cosmos Reason2 8B base-experiment identifier. Admin-managed "
            "mode only: the workspace UUID the admin reported back; the "
            "CLI patches it across all project DBs. Ignored in "
            "self-service mode (provisioning discovers UUIDs itself)."
        ),
    )
    tao_parser.add_argument(
        "--base-experiment-id-2b",
        default=None,
        help=(
            "Cosmos Reason2 2B base-experiment identifier — same semantics "
            "as --base-experiment-id-8b."
        ),
    )
    tao_parser.add_argument(
        "--base-experiment-id-cosmos3-nano",
        default=None,
        help=(
            "Cosmos 3 Nano-Reasoner (nvidia/Cosmos3-Nano-Reasoner) "
            "base-experiment identifier. Admin-managed mode: the workspace "
            "UUID the admin reported back; the CLI patches it across all "
            "project DBs."
        ),
    )
    tao_parser.add_argument(
        "--base-experiment-id-cosmos3-super",
        default=None,
        help=(
            "Cosmos 3 Super-Reasoner (nvidia/Cosmos3-Super-Reasoner) "
            "base-experiment identifier — same semantics as "
            "--base-experiment-id-cosmos3-nano."
        ),
    )
    mode_group = tao_parser.add_mutually_exclusive_group()
    mode_group.add_argument(
        "--self-service",
        dest="admin_managed",
        action="store_false",
        default=False,
        help=(
            "(default) Let Student Training provision selected missing bases "
            "on first use."
        ),
    )
    tao_parser.add_argument(
        "--eager-bases",
        action="store_true",
        help=(
            "In self-service mode, provision every supported Student base "
            "during bootstrap instead of waiting for first use."
        ),
    )
    mode_group.add_argument(
        "--admin-managed",
        dest="admin_managed",
        action="store_true",
        help=(
            "Create the workspace only; expect admin-supplied UUIDs via "
            "--base-experiment-id-{2b,8b}. See "
            "docs/tao-ftms-install.md (base-experiment registration)."
        ),
    )
    tao_parser.set_defaults(func=cmd_tao_bootstrap)

    pull_parser = subparsers.add_parser(
        "tao-pull-base-experiments",
        help=(
            "Self-service base-experiment provisioning. "
            "Requires a bootstrapped workspace."
        ),
    )
    pull_parser.add_argument(
        "--model-config-id",
        action="append",
        default=[],
        help=(
            "Repeatable. Limits provisioning to specific ModelConfig rows. "
            "Default: every seeded student_base entry the Blueprint knows "
            "how to pull (Cosmos Reason2 2B + 8B)."
        ),
    )
    pull_parser.add_argument(
        "--skip-install",
        action="store_true",
        help=(
            "Run the helper with the current Python interpreter instead of "
            "the default isolated uv environment. Use only when the TAO "
            "packaging dependencies are managed out-of-band."
        ),
    )
    pull_parser.add_argument(
        "--dry-run",
        action="store_true",
        help=(
            "Stop after the subprocess driver succeeds. Skips S3 upload "
            "and `:load_airgapped`. Useful for proving NGC key + HF "
            "reachability without paying the workspace upload cost."
        ),
    )
    pull_parser.add_argument(
        "--timeout-download-s",
        type=float,
        default=1800.0,
        help="Subprocess deadline in seconds (default 1800 = 30 min).",
    )
    pull_parser.set_defaults(func=cmd_tao_pull_base_experiments)

    # The curated public export omits the optional AutoRun operator feature.
    autorun_module_name = "vlm_feedback_loop.cli_autorun"
    if util.find_spec(autorun_module_name) is not None:
        autorun_module = import_module(autorun_module_name)
        add_autorun_subparser = cast(
            "Callable[[Any], argparse.ArgumentParser]",
            autorun_module.add_autorun_subparser,
        )
        add_autorun_subparser(subparsers)

    args = parser.parse_args(cli_argv)
    if not hasattr(args, "func"):
        parser.print_help()
        sys.exit(1)

    args.func(args)


if __name__ == "__main__":
    main()
